name: Run Main

on:
  schedule:
    - cron: "10 7 * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  STEAMAPIKEY: ${{ secrets.STEAMAPIKEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v3.5.3
      with:
        ref: ${{ github.head_ref }}

    # Run using Python 3.11.4 for consistency
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v4.3.0
      with:
        python-version: '3.11.4'
        architecture: 'x64'

    # Cache dependencies. From:
    # https://github.com/actions/cache/blob/master/examples.md#python---pip
    - uses: actions/cache@v3.0.11
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    # Install dependencies with `pip`
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt
    # Generate all statistics images
    - name: Run Main.py
      run: |
        python3 --version
        python3 src/main.py

    # Commit all changed files to the repository
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update User Playtime files
        commit_user_name: BOT-Carter4242
        commit_user_email: 115385416+BOT-Carter4242@users.noreply.github.com
        commit_author: Author <actions@github.com>
